// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOwnersOfTeam = `-- name: CountOwnersOfTeam :one
SELECT count(*) FROM memberships WHERE owner_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnersOfTeam(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersOfTeam, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, display_name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET display_name = excluded.display_name, updated_at = now()
RETURNING id, display_name, email, created_at, updated_at
`

type CreateTeamParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.ID, arg.DisplayName)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND owner_id = $2
`

type DeleteMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.OwnerID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, owner_id, role, created_at FROM memberships WHERE user_id = $1 AND owner_id = $2
`

type GetMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OwnerID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.OwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, display_name, email, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at FROM users WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersOfTeam = `-- name: ListMembersOfTeam :many
SELECT m.user_id, m.owner_id, m.role, m.created_at, u.email, u.display_name AS user_name
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.owner_id = $1
ORDER BY u.email
`

type ListMembersOfTeamRow struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
	Email     string
	UserName  string
}

func (q *Queries) ListMembersOfTeam(ctx context.Context, ownerID string) ([]ListMembersOfTeamRow, error) {
	rows, err := q.db.Query(ctx, listMembersOfTeam, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersOfTeamRow{}
	for rows.Next() {
		var i ListMembersOfTeamRow
		if err := rows.Scan(
			&i.UserID,
			&i.OwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT m.user_id, m.owner_id, m.role, m.created_at, t.display_name AS team_name
FROM memberships m
JOIN teams t ON t.id = m.owner_id
WHERE m.user_id = $1
ORDER BY t.display_name
`

type ListMembershipsForUserRow struct {
	UserID    uuid.UUID
	OwnerID   string
	Role      string
	CreatedAt time.Time
	TeamName  string
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForUserRow{}
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.OwnerID,
			&i.Role,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeam = `-- name: LockTeam :one
SELECT id, display_name, email, created_at, updated_at FROM teams WHERE id = $1 FOR UPDATE
`

// A role change reads the owner count and then writes; taking the team row
// first serialises those pairs, so two concurrent demotions cannot both see
// two owners and both proceed.
func (q *Queries) LockTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, lockTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO memberships (user_id, owner_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, owner_id) DO UPDATE SET role = excluded.role
RETURNING user_id, owner_id, role, created_at
`

type UpsertMembershipParams struct {
	UserID  uuid.UUID
	OwnerID string
	Role    string
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, upsertMembership, arg.UserID, arg.OwnerID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.OwnerID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (email, display_name)
VALUES (lower($1::text), $2)
ON CONFLICT (lower(email)) DO UPDATE
SET display_name = CASE
        WHEN excluded.display_name <> '' THEN excluded.display_name
        ELSE users.display_name
    END,
    updated_at = now()
RETURNING id, email, display_name, totp_secret, totp_confirmed, created_at, updated_at
`

type UpsertUserParams struct {
	Email       string
	DisplayName string
}

// Users and sessions carry no owner_id: a person exists before they belong to
// any team. Memberships and invitations do, and stay scoped by it like
// everything else.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TotpSecret,
		&i.TotpConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
