// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countApps = `-- name: CountApps :one
SELECT count(*) FROM apps WHERE owner_id = $1
`

func (q *Queries) CountApps(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countApps, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    owner_id, name, namespace, image, replicas, port, source, internal,
    cpu_request, cpu_limit, memory_request, memory_limit, project_id,
    repo_url, repo_branch, repo_subdir
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id
`

type CreateAppParams struct {
	OwnerID       string
	Name          string
	Namespace     string
	Image         string
	Replicas      int32
	Port          int32
	Source        string
	Internal      bool
	CpuRequest    string
	CpuLimit      string
	MemoryRequest string
	MemoryLimit   string
	ProjectID     pgtype.UUID
	RepoUrl       string
	RepoBranch    string
	RepoSubdir    string
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.OwnerID,
		arg.Name,
		arg.Namespace,
		arg.Image,
		arg.Replicas,
		arg.Port,
		arg.Source,
		arg.Internal,
		arg.CpuRequest,
		arg.CpuLimit,
		arg.MemoryRequest,
		arg.MemoryLimit,
		arg.ProjectID,
		arg.RepoUrl,
		arg.RepoBranch,
		arg.RepoSubdir,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    owner_id, app_id, image, revision, status, release_id, trigger,
    actor_kind, actor_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9
)
RETURNING id, owner_id, app_id, image, revision, status, message, started_at, finished_at, release_id, trigger, actor_kind, actor_id
`

type CreateDeploymentParams struct {
	OwnerID   string
	AppID     uuid.UUID
	Image     string
	Revision  string
	Status    string
	ReleaseID pgtype.UUID
	Trigger   string
	ActorKind string
	ActorID   string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.OwnerID,
		arg.AppID,
		arg.Image,
		arg.Revision,
		arg.Status,
		arg.ReleaseID,
		arg.Trigger,
		arg.ActorKind,
		arg.ActorID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Image,
		&i.Revision,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ReleaseID,
		&i.Trigger,
		&i.ActorKind,
		&i.ActorID,
	)
	return i, err
}

const createTeamRow = `-- name: CreateTeamRow :one

INSERT INTO teams (id, display_name, email)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        email        = EXCLUDED.email,
        updated_at   = now()
RETURNING id, display_name, email, created_at, updated_at
`

type CreateTeamRowParams struct {
	ID          string
	DisplayName string
	Email       string
}

// Every query filters by owner_id.
//
// This is not defensive duplication of an application-level check — it is the
// check. A handler that forgets to scope produces no rows here rather than
// another owner's data, and sqlc makes the parameter impossible to omit
// because the generated signature requires it.
func (q *Queries) CreateTeamRow(ctx context.Context, arg CreateTeamRowParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeamRow, arg.ID, arg.DisplayName, arg.Email)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM apps WHERE owner_id = $1 AND id = $2
`

type DeleteAppParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) DeleteApp(ctx context.Context, arg DeleteAppParams) error {
	_, err := q.db.Exec(ctx, deleteApp, arg.OwnerID, arg.ID)
	return err
}

const deployActivity = `-- name: DeployActivity :many
SELECT date_trunc('day', started_at)::timestamptz AS day,
       status,
       count(*)::bigint AS total
FROM deployments
WHERE owner_id = $1 AND started_at >= $2
GROUP BY 1, 2
ORDER BY 1
`

type DeployActivityParams struct {
	OwnerID   string
	StartedAt time.Time
}

type DeployActivityRow struct {
	Day    time.Time
	Status string
	Total  int64
}

// Deploys per day and outcome, for the overview chart.
//
// Counted in the database rather than by reading rows and tallying them in Go:
// a busy month is thousands of deployments, and none of them are wanted here
// except as a number.
//
// Days with no deploys are absent from this result. The caller fills them in;
// see app.DeployActivity for why that cannot be skipped.
func (q *Queries) DeployActivity(ctx context.Context, arg DeployActivityParams) ([]DeployActivityRow, error) {
	rows, err := q.db.Query(ctx, deployActivity, arg.OwnerID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployActivityRow{}
	for rows.Next() {
		var i DeployActivityRow
		if err := rows.Scan(&i.Day, &i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishDeployment = `-- name: FinishDeployment :one
UPDATE deployments
SET status = $3, message = $4, finished_at = now()
WHERE owner_id = $1 AND id = $2
RETURNING id, owner_id, app_id, image, revision, status, message, started_at, finished_at, release_id, trigger, actor_kind, actor_id
`

type FinishDeploymentParams struct {
	OwnerID string
	ID      uuid.UUID
	Status  string
	Message string
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, finishDeployment,
		arg.OwnerID,
		arg.ID,
		arg.Status,
		arg.Message,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Image,
		&i.Revision,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ReleaseID,
		&i.Trigger,
		&i.ActorKind,
		&i.ActorID,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id FROM apps
WHERE owner_id = $1 AND name = $2
`

type GetAppParams struct {
	OwnerID string
	Name    string
}

func (q *Queries) GetApp(ctx context.Context, arg GetAppParams) (App, error) {
	row := q.db.QueryRow(ctx, getApp, arg.OwnerID, arg.Name)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id FROM apps
WHERE owner_id = $1 AND id = $2
`

type GetAppByIDParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) GetAppByID(ctx context.Context, arg GetAppByIDParams) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, arg.OwnerID, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, owner_id, app_id, image, revision, status, message, started_at, finished_at, release_id, trigger, actor_kind, actor_id FROM deployments
WHERE owner_id = $1 AND id = $2
`

type GetDeploymentParams struct {
	OwnerID string
	ID      uuid.UUID
}

func (q *Queries) GetDeployment(ctx context.Context, arg GetDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, arg.OwnerID, arg.ID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Image,
		&i.Revision,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ReleaseID,
		&i.Trigger,
		&i.ActorKind,
		&i.ActorID,
	)
	return i, err
}

const getTeamRow = `-- name: GetTeamRow :one
SELECT id, display_name, email, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamRow(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamRow, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCNAMEAppConfigVersions = `-- name: IncrementCNAMEAppConfigVersions :exec
UPDATE apps
SET config_version = config_version + 1, updated_at = now()
WHERE cname_only
`

// The platform CNAME target is an install-wide live overlay, but it only
// renders into apps that explicitly opted into CNAME routing.
func (q *Queries) IncrementCNAMEAppConfigVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, incrementCNAMEAppConfigVersions)
	return err
}

const incrementGitAppConfigVersions = `-- name: IncrementGitAppConfigVersions :exec
UPDATE apps
SET config_version = config_version + 1, updated_at = now()
WHERE source = 'git'
`

// Registry credentials are a live overlay for every Git-built image. They are
// install-wide, so one settings mutation invalidates each Git app exactly
// once without manufacturing release history.
func (q *Queries) IncrementGitAppConfigVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, incrementGitAppConfigVersions)
	return err
}

const listApps = `-- name: ListApps :many
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id FROM apps
WHERE owner_id = $1
ORDER BY name
`

func (q *Queries) ListApps(ctx context.Context, ownerID string) ([]App, error) {
	rows, err := q.db.Query(ctx, listApps, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Namespace,
			&i.Image,
			&i.Replicas,
			&i.Port,
			&i.CpuRequest,
			&i.CpuLimit,
			&i.MemoryRequest,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HealthPath,
			&i.HealthLiveness,
			&i.Source,
			&i.Internal,
			&i.ProjectID,
			&i.CanvasX,
			&i.CanvasY,
			&i.HttpsOnly,
			&i.CnameOnly,
			&i.RepoUrl,
			&i.RepoBranch,
			&i.RepoSubdir,
			&i.RunAsUser,
			&i.ConfigVersion,
			&i.ActiveReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsForReconciliation = `-- name: ListAppsForReconciliation :many
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id FROM apps
WHERE active_release_id IS NOT NULL
   OR EXISTS (
       SELECT 1 FROM deployment_operations o
       WHERE o.app_id = apps.id AND o.owner_id = apps.owner_id
         AND o.status = 'queued' AND o.checkpoint IN ('applying', 'verifying')
   )
ORDER BY id
`

// Apps whose database pointer names the workload the cluster must converge to.
// This is intentionally install-scoped: the reconciler acts from stored
// ownership rather than from an authenticated request.
func (q *Queries) ListAppsForReconciliation(ctx context.Context) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsForReconciliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Namespace,
			&i.Image,
			&i.Replicas,
			&i.Port,
			&i.CpuRequest,
			&i.CpuLimit,
			&i.MemoryRequest,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HealthPath,
			&i.HealthLiveness,
			&i.Source,
			&i.Internal,
			&i.ProjectID,
			&i.CanvasX,
			&i.CanvasY,
			&i.HttpsOnly,
			&i.CnameOnly,
			&i.RepoUrl,
			&i.RepoBranch,
			&i.RepoSubdir,
			&i.RunAsUser,
			&i.ConfigVersion,
			&i.ActiveReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsWithLastDeploy = `-- name: ListAppsWithLastDeploy :many
SELECT a.id, a.owner_id, a.name, a.namespace, a.image, a.replicas, a.port, a.cpu_request, a.cpu_limit, a.memory_request, a.memory_limit, a.created_at, a.updated_at, a.health_path, a.health_liveness, a.source, a.internal, a.project_id, a.canvas_x, a.canvas_y, a.https_only, a.cname_only, a.repo_url, a.repo_branch, a.repo_subdir, a.run_as_user, a.config_version, a.active_release_id, d.status AS last_deploy_status
FROM apps a
LEFT JOIN LATERAL (
    SELECT status FROM deployments
    WHERE app_id = a.id
    ORDER BY started_at DESC
    LIMIT 1
) d ON true
WHERE a.owner_id = $1
ORDER BY a.name
`

type ListAppsWithLastDeployRow struct {
	App              App
	LastDeployStatus string
}

// Every app, with how its most recent deployment ended.
//
// A failed deploy leaves the previous workload running, so the app's live
// status stays green and nothing in a list of apps says the last attempt to
// change it did not take. That is exactly the deploy somebody needs to find,
// and until this query existed the only way to find it was to open each app.
//
// LATERAL rather than a window function or a join on max(started_at): one index
// lookup per app, and it reads as what it is — the latest row for this app.
func (q *Queries) ListAppsWithLastDeploy(ctx context.Context, ownerID string) ([]ListAppsWithLastDeployRow, error) {
	rows, err := q.db.Query(ctx, listAppsWithLastDeploy, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsWithLastDeployRow{}
	for rows.Next() {
		var i ListAppsWithLastDeployRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.OwnerID,
			&i.App.Name,
			&i.App.Namespace,
			&i.App.Image,
			&i.App.Replicas,
			&i.App.Port,
			&i.App.CpuRequest,
			&i.App.CpuLimit,
			&i.App.MemoryRequest,
			&i.App.MemoryLimit,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.HealthPath,
			&i.App.HealthLiveness,
			&i.App.Source,
			&i.App.Internal,
			&i.App.ProjectID,
			&i.App.CanvasX,
			&i.App.CanvasY,
			&i.App.HttpsOnly,
			&i.App.CnameOnly,
			&i.App.RepoUrl,
			&i.App.RepoBranch,
			&i.App.RepoSubdir,
			&i.App.RunAsUser,
			&i.App.ConfigVersion,
			&i.App.ActiveReleaseID,
			&i.LastDeployStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, owner_id, app_id, image, revision, status, message, started_at, finished_at, release_id, trigger, actor_kind, actor_id FROM deployments
WHERE owner_id = $1 AND app_id = $2
ORDER BY started_at DESC
LIMIT $3
`

type ListDeploymentsParams struct {
	OwnerID string
	AppID   uuid.UUID
	Limit   int32
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeployments, arg.OwnerID, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Image,
			&i.Revision,
			&i.Status,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ReleaseID,
			&i.Trigger,
			&i.ActorKind,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployments = `-- name: ListRecentDeployments :many
SELECT d.id, d.owner_id, d.app_id, d.image, d.revision, d.status, d.message, d.started_at, d.finished_at, d.release_id, d.trigger, d.actor_kind, d.actor_id, a.name AS app_name, a.namespace AS app_namespace,
       a.active_release_id
FROM deployments d
JOIN apps a ON a.id = d.app_id AND a.owner_id = d.owner_id
WHERE d.owner_id = $1
ORDER BY d.started_at DESC
LIMIT $2
`

type ListRecentDeploymentsParams struct {
	OwnerID string
	Limit   int32
}

type ListRecentDeploymentsRow struct {
	ID              uuid.UUID
	OwnerID         string
	AppID           uuid.UUID
	Image           string
	Revision        string
	Status          string
	Message         string
	StartedAt       time.Time
	FinishedAt      pgtype.Timestamptz
	ReleaseID       pgtype.UUID
	Trigger         string
	ActorKind       string
	ActorID         string
	AppName         string
	AppNamespace    string
	ActiveReleaseID pgtype.UUID
}

// Joined to apps so the activity feed can name the workload without a second
// round trip per row. The join is on app_id AND owner_id: joining on app_id
// alone would be correct today and wrong the moment more than one owner exists.
func (q *Queries) ListRecentDeployments(ctx context.Context, arg ListRecentDeploymentsParams) ([]ListRecentDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentDeployments, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDeploymentsRow{}
	for rows.Next() {
		var i ListRecentDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Image,
			&i.Revision,
			&i.Status,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ReleaseID,
			&i.Trigger,
			&i.ActorKind,
			&i.ActorID,
			&i.AppName,
			&i.AppNamespace,
			&i.ActiveReleaseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppHealth = `-- name: SetAppHealth :one
UPDATE apps
SET health_path     = $1,
    health_liveness = $2,
    config_version  = config_version + 1,
    updated_at      = now()
WHERE owner_id = $3 AND id = $4
  AND (health_path, health_liveness)
      IS DISTINCT FROM ($1, $2)
RETURNING id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id
`

type SetAppHealthParams struct {
	HealthPath     string
	HealthLiveness bool
	OwnerID        string
	ID             uuid.UUID
}

func (q *Queries) SetAppHealth(ctx context.Context, arg SetAppHealthParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppHealth,
		arg.HealthPath,
		arg.HealthLiveness,
		arg.OwnerID,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const setAppImage = `-- name: SetAppImage :one
UPDATE apps
SET image = $3, config_version = config_version + 1, updated_at = now()
WHERE owner_id = $1 AND id = $2 AND image IS DISTINCT FROM $3
RETURNING id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id
`

type SetAppImageParams struct {
	OwnerID string
	ID      uuid.UUID
	Image   string
}

// The image a build produced. Separate from UpdateApp because a build sets
// only this: the replicas and limits a person configured are not a build's to
// overwrite, and passing them through would make every build a chance to.
func (q *Queries) SetAppImage(ctx context.Context, arg SetAppImageParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppImage, arg.OwnerID, arg.ID, arg.Image)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const setAppNetworking = `-- name: SetAppNetworking :execrows
UPDATE apps
SET https_only = $1, cname_only = $2,
    config_version = config_version + 1, updated_at = now()
WHERE owner_id = $3 AND name = $4
  AND (https_only, cname_only) IS DISTINCT FROM ($1, $2)
`

type SetAppNetworkingParams struct {
	HttpsOnly bool
	CnameOnly bool
	OwnerID   string
	Name      string
}

func (q *Queries) SetAppNetworking(ctx context.Context, arg SetAppNetworkingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppNetworking,
		arg.HttpsOnly,
		arg.CnameOnly,
		arg.OwnerID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppReplicas = `-- name: SetAppReplicas :one
UPDATE apps
SET replicas = $3, config_version = config_version + 1, updated_at = now()
WHERE owner_id = $1 AND id = $2 AND replicas IS DISTINCT FROM $3
RETURNING id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id
`

type SetAppReplicasParams struct {
	OwnerID  string
	ID       uuid.UUID
	Replicas int32
}

func (q *Queries) SetAppReplicas(ctx context.Context, arg SetAppReplicasParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppReplicas, arg.OwnerID, arg.ID, arg.Replicas)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const setAppRunAsUser = `-- name: SetAppRunAsUser :exec
UPDATE apps
SET run_as_user = $1,
    updated_at = now()
WHERE owner_id = $2 AND id = $3
  AND run_as_user IS DISTINCT FROM $1
`

type SetAppRunAsUserParams struct {
	RunAsUser int64
	OwnerID   string
	ID        uuid.UUID
}

// Recorded by a build, which is the only thing that can discover it. The
// image update owns the build operation's single config_version increment.
func (q *Queries) SetAppRunAsUser(ctx context.Context, arg SetAppRunAsUserParams) error {
	_, err := q.db.Exec(ctx, setAppRunAsUser, arg.RunAsUser, arg.OwnerID, arg.ID)
	return err
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps
SET image          = $1,
    port           = $2,
    cpu_request    = $3,
    cpu_limit      = $4,
    memory_request = $5,
    memory_limit   = $6,
    internal       = $7,
    repo_url       = $8,
    repo_branch    = $9,
    repo_subdir    = $10,
    config_version = config_version + 1,
    updated_at     = now()
WHERE owner_id = $11 AND id = $12
  AND (image, port, cpu_request, cpu_limit, memory_request, memory_limit,
       internal, repo_url, repo_branch, repo_subdir)
      IS DISTINCT FROM
      ($1, $2, $3, $4, $5, $6,
       $7, $8, $9, $10)
RETURNING id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id
`

type UpdateAppParams struct {
	Image         string
	Port          int32
	CpuRequest    string
	CpuLimit      string
	MemoryRequest string
	MemoryLimit   string
	Internal      bool
	RepoUrl       string
	RepoBranch    string
	RepoSubdir    string
	OwnerID       string
	ID            uuid.UUID
}

// Everything about an app a person is allowed to change after creating it.
//
// Deliberately not replicas: scaling has its own query because it has its own
// rule about storage, and folding it in here would make every settings save a
// chance to silently reset a scale somebody had chosen.
//
// Nor the health probe, the networking toggles or run_as_user — each of those
// already has a query shaped to what it means, and this one exists for the
// fields that had no way to be changed at all.
func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.Image,
		arg.Port,
		arg.CpuRequest,
		arg.CpuLimit,
		arg.MemoryRequest,
		arg.MemoryLimit,
		arg.Internal,
		arg.RepoUrl,
		arg.RepoBranch,
		arg.RepoSubdir,
		arg.OwnerID,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}
