// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingReleaseBackfills = `-- name: CountPendingReleaseBackfills :one
SELECT count(*) FROM app_release_backfills WHERE state = 'pending'
`

func (q *Queries) CountPendingReleaseBackfills(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReleaseBackfills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppRelease = `-- name: CreateAppRelease :one

INSERT INTO app_releases (
    owner_id, app_id, image_ref, image_digest, source, source_revision,
    replicas, port, cpu_request, cpu_limit, memory_request, memory_limit,
    internal, run_as_user, fs_group, scratch_paths,
    writable_root_filesystem, health_path, health_liveness,
    env, secret_keys, config_version, origin
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22, $23
)
RETURNING id, owner_id, app_id, image_ref, image_digest, source, source_revision, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, internal, run_as_user, fs_group, scratch_paths, writable_root_filesystem, health_path, health_liveness, env, secret_keys, config_version, created_at, origin
`

type CreateAppReleaseParams struct {
	OwnerID                string
	AppID                  uuid.UUID
	ImageRef               string
	ImageDigest            string
	Source                 string
	SourceRevision         string
	Replicas               int32
	Port                   int32
	CpuRequest             string
	CpuLimit               string
	MemoryRequest          string
	MemoryLimit            string
	Internal               bool
	RunAsUser              int64
	FsGroup                int64
	ScratchPaths           []string
	WritableRootFilesystem bool
	HealthPath             string
	HealthLiveness         bool
	Env                    []byte
	SecretKeys             []string
	ConfigVersion          int64
	Origin                 string
}

// Release snapshots are owner-scoped at every read and write, like every
// other resource. There is intentionally no update query: a release is a fact
// about a past deployment, not editable configuration.
func (q *Queries) CreateAppRelease(ctx context.Context, arg CreateAppReleaseParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, createAppRelease,
		arg.OwnerID,
		arg.AppID,
		arg.ImageRef,
		arg.ImageDigest,
		arg.Source,
		arg.SourceRevision,
		arg.Replicas,
		arg.Port,
		arg.CpuRequest,
		arg.CpuLimit,
		arg.MemoryRequest,
		arg.MemoryLimit,
		arg.Internal,
		arg.RunAsUser,
		arg.FsGroup,
		arg.ScratchPaths,
		arg.WritableRootFilesystem,
		arg.HealthPath,
		arg.HealthLiveness,
		arg.Env,
		arg.SecretKeys,
		arg.ConfigVersion,
		arg.Origin,
	)
	var i AppRelease
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.Source,
		&i.SourceRevision,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.Internal,
		&i.RunAsUser,
		&i.FsGroup,
		&i.ScratchPaths,
		&i.WritableRootFilesystem,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Env,
		&i.SecretKeys,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.Origin,
	)
	return i, err
}

const getAppForReleaseBackfill = `-- name: GetAppForReleaseBackfill :one
SELECT id, owner_id, name, namespace, image, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, created_at, updated_at, health_path, health_liveness, source, internal, project_id, canvas_x, canvas_y, https_only, cname_only, repo_url, repo_branch, repo_subdir, run_as_user, config_version, active_release_id FROM apps
WHERE owner_id = $1 AND id = $2
FOR UPDATE
`

type GetAppForReleaseBackfillParams struct {
	OwnerID string
	AppID   uuid.UUID
}

func (q *Queries) GetAppForReleaseBackfill(ctx context.Context, arg GetAppForReleaseBackfillParams) (App, error) {
	row := q.db.QueryRow(ctx, getAppForReleaseBackfill, arg.OwnerID, arg.AppID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Namespace,
		&i.Image,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Source,
		&i.Internal,
		&i.ProjectID,
		&i.CanvasX,
		&i.CanvasY,
		&i.HttpsOnly,
		&i.CnameOnly,
		&i.RepoUrl,
		&i.RepoBranch,
		&i.RepoSubdir,
		&i.RunAsUser,
		&i.ConfigVersion,
		&i.ActiveReleaseID,
	)
	return i, err
}

const getAppRelease = `-- name: GetAppRelease :one
SELECT id, owner_id, app_id, image_ref, image_digest, source, source_revision, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, internal, run_as_user, fs_group, scratch_paths, writable_root_filesystem, health_path, health_liveness, env, secret_keys, config_version, created_at, origin FROM app_releases
WHERE owner_id = $1 AND app_id = $2 AND id = $3
`

type GetAppReleaseParams struct {
	OwnerID string
	AppID   uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetAppRelease(ctx context.Context, arg GetAppReleaseParams) (AppRelease, error) {
	row := q.db.QueryRow(ctx, getAppRelease, arg.OwnerID, arg.AppID, arg.ID)
	var i AppRelease
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.Source,
		&i.SourceRevision,
		&i.Replicas,
		&i.Port,
		&i.CpuRequest,
		&i.CpuLimit,
		&i.MemoryRequest,
		&i.MemoryLimit,
		&i.Internal,
		&i.RunAsUser,
		&i.FsGroup,
		&i.ScratchPaths,
		&i.WritableRootFilesystem,
		&i.HealthPath,
		&i.HealthLiveness,
		&i.Env,
		&i.SecretKeys,
		&i.ConfigVersion,
		&i.CreatedAt,
		&i.Origin,
	)
	return i, err
}

const getReleaseBackfillState = `-- name: GetReleaseBackfillState :one
SELECT app_id, owner_id, state, last_error, attempts, next_attempt_at, updated_at FROM app_release_backfills
WHERE owner_id = $1 AND app_id = $2
`

type GetReleaseBackfillStateParams struct {
	OwnerID string
	AppID   uuid.UUID
}

func (q *Queries) GetReleaseBackfillState(ctx context.Context, arg GetReleaseBackfillStateParams) (AppReleaseBackfill, error) {
	row := q.db.QueryRow(ctx, getReleaseBackfillState, arg.OwnerID, arg.AppID)
	var i AppReleaseBackfill
	err := row.Scan(
		&i.AppID,
		&i.OwnerID,
		&i.State,
		&i.LastError,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAppConfigVersion = `-- name: IncrementAppConfigVersion :one
UPDATE apps
SET config_version = config_version + 1, updated_at = now()
WHERE owner_id = $1 AND id = $2
RETURNING config_version
`

type IncrementAppConfigVersionParams struct {
	OwnerID string
	AppID   uuid.UUID
}

func (q *Queries) IncrementAppConfigVersion(ctx context.Context, arg IncrementAppConfigVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementAppConfigVersion, arg.OwnerID, arg.AppID)
	var config_version int64
	err := row.Scan(&config_version)
	return config_version, err
}

const listAppReleases = `-- name: ListAppReleases :many
SELECT id, owner_id, app_id, image_ref, image_digest, source, source_revision, replicas, port, cpu_request, cpu_limit, memory_request, memory_limit, internal, run_as_user, fs_group, scratch_paths, writable_root_filesystem, health_path, health_liveness, env, secret_keys, config_version, created_at, origin FROM app_releases
WHERE owner_id = $1 AND app_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAppReleasesParams struct {
	OwnerID     string
	AppID       uuid.UUID
	ResultLimit int32
}

func (q *Queries) ListAppReleases(ctx context.Context, arg ListAppReleasesParams) ([]AppRelease, error) {
	rows, err := q.db.Query(ctx, listAppReleases, arg.OwnerID, arg.AppID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppRelease{}
	for rows.Next() {
		var i AppRelease
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.ImageRef,
			&i.ImageDigest,
			&i.Source,
			&i.SourceRevision,
			&i.Replicas,
			&i.Port,
			&i.CpuRequest,
			&i.CpuLimit,
			&i.MemoryRequest,
			&i.MemoryLimit,
			&i.Internal,
			&i.RunAsUser,
			&i.FsGroup,
			&i.ScratchPaths,
			&i.WritableRootFilesystem,
			&i.HealthPath,
			&i.HealthLiveness,
			&i.Env,
			&i.SecretKeys,
			&i.ConfigVersion,
			&i.CreatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReleaseBackfills = `-- name: ListPendingReleaseBackfills :many
SELECT a.id, a.owner_id, a.name, a.namespace, a.image, a.replicas, a.port, a.cpu_request, a.cpu_limit, a.memory_request, a.memory_limit, a.created_at, a.updated_at, a.health_path, a.health_liveness, a.source, a.internal, a.project_id, a.canvas_x, a.canvas_y, a.https_only, a.cname_only, a.repo_url, a.repo_branch, a.repo_subdir, a.run_as_user, a.config_version, a.active_release_id, b.state, b.last_error, b.attempts
FROM app_release_backfills b
JOIN apps a ON a.id = b.app_id AND a.owner_id = b.owner_id
WHERE b.state IN ('pending', 'image_unavailable', 'blocked')
  AND b.next_attempt_at <= now()
  AND a.active_release_id IS NULL
ORDER BY b.next_attempt_at, b.app_id
LIMIT $1
`

type ListPendingReleaseBackfillsRow struct {
	App       App
	State     string
	LastError string
	Attempts  int32
}

func (q *Queries) ListPendingReleaseBackfills(ctx context.Context, resultLimit int32) ([]ListPendingReleaseBackfillsRow, error) {
	rows, err := q.db.Query(ctx, listPendingReleaseBackfills, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReleaseBackfillsRow{}
	for rows.Next() {
		var i ListPendingReleaseBackfillsRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.OwnerID,
			&i.App.Name,
			&i.App.Namespace,
			&i.App.Image,
			&i.App.Replicas,
			&i.App.Port,
			&i.App.CpuRequest,
			&i.App.CpuLimit,
			&i.App.MemoryRequest,
			&i.App.MemoryLimit,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.HealthPath,
			&i.App.HealthLiveness,
			&i.App.Source,
			&i.App.Internal,
			&i.App.ProjectID,
			&i.App.CanvasX,
			&i.App.CanvasY,
			&i.App.HttpsOnly,
			&i.App.CnameOnly,
			&i.App.RepoUrl,
			&i.App.RepoBranch,
			&i.App.RepoSubdir,
			&i.App.RunAsUser,
			&i.App.ConfigVersion,
			&i.App.ActiveReleaseID,
			&i.State,
			&i.LastError,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const normalizeLegacyDeploymentStatuses = `-- name: NormalizeLegacyDeploymentStatuses :execrows
UPDATE deployments
SET status = 'succeeded', finished_at = COALESCE(finished_at, started_at)
WHERE status IN ('active', 'superseded')
`

func (q *Queries) NormalizeLegacyDeploymentStatuses(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, normalizeLegacyDeploymentStatuses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveRelease = `-- name: SetActiveRelease :execrows
UPDATE apps
SET active_release_id = $1, updated_at = now()
WHERE apps.owner_id = $2 AND apps.id = $3
  AND EXISTS (
      SELECT 1 FROM app_releases r
      WHERE r.id = $1 AND r.owner_id = $2
        AND r.app_id = $3
  )
`

type SetActiveReleaseParams struct {
	ReleaseID pgtype.UUID
	OwnerID   string
	AppID     uuid.UUID
}

func (q *Queries) SetActiveRelease(ctx context.Context, arg SetActiveReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActiveRelease, arg.ReleaseID, arg.OwnerID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDeploymentRelease = `-- name: SetDeploymentRelease :execrows
UPDATE deployments
SET release_id = $1
WHERE deployments.owner_id = $2 AND deployments.id = $3
  AND deployments.release_id IS NULL
  AND EXISTS (
      SELECT 1 FROM app_releases r
      WHERE r.id = $1 AND r.owner_id = $2
        AND r.app_id = deployments.app_id
  )
`

type SetDeploymentReleaseParams struct {
	ReleaseID    pgtype.UUID
	OwnerID      string
	DeploymentID uuid.UUID
}

func (q *Queries) SetDeploymentRelease(ctx context.Context, arg SetDeploymentReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeploymentRelease, arg.ReleaseID, arg.OwnerID, arg.DeploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReleaseBackfillState = `-- name: SetReleaseBackfillState :execrows
UPDATE app_release_backfills
SET state = $1, last_error = $2,
    attempts = attempts + 1,
    next_attempt_at = CASE
        WHEN $1 = 'pending' THEN now() + interval '1 minute'
        WHEN $1 IN ('image_unavailable', 'blocked')
            THEN now() + interval '15 minutes'
        ELSE now()
    END,
    updated_at = now()
WHERE owner_id = $3 AND app_id = $4
`

type SetReleaseBackfillStateParams struct {
	State     string
	LastError string
	OwnerID   string
	AppID     uuid.UUID
}

func (q *Queries) SetReleaseBackfillState(ctx context.Context, arg SetReleaseBackfillStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReleaseBackfillState,
		arg.State,
		arg.LastError,
		arg.OwnerID,
		arg.AppID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
