// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variables.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteVariable = `-- name: DeleteVariable :execrows
DELETE FROM variables
WHERE owner_id = $1 AND app_id = $2 AND key = $3
`

type DeleteVariableParams struct {
	OwnerID string
	AppID   uuid.UUID
	Key     string
}

func (q *Queries) DeleteVariable(ctx context.Context, arg DeleteVariableParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVariable, arg.OwnerID, arg.AppID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVariablesForApp = `-- name: ListVariablesForApp :many
SELECT id, owner_id, app_id, key, value, sealed, secret, created_at, updated_at FROM variables WHERE app_id = $1 ORDER BY key
`

func (q *Queries) ListVariablesForApp(ctx context.Context, appID uuid.UUID) ([]Variable, error) {
	rows, err := q.db.Query(ctx, listVariablesForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variable{}
	for rows.Next() {
		var i Variable
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Key,
			&i.Value,
			&i.Sealed,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVariable = `-- name: UpsertVariable :one

INSERT INTO variables (owner_id, app_id, key, value, sealed, secret)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (app_id, key) DO UPDATE
SET value      = excluded.value,
    sealed     = excluded.sealed,
    secret     = excluded.secret,
    updated_at = now()
RETURNING id, owner_id, app_id, key, value, sealed, secret, created_at, updated_at
`

type UpsertVariableParams struct {
	OwnerID string
	AppID   uuid.UUID
	Key     string
	Value   string
	Sealed  []byte
	Secret  bool
}

// Environment variables, one row each so a secret can be sealed while its
// neighbour stays readable.
// Upsert rather than insert: setting a variable that already exists is what a
// person means by editing one, and a separate update path would need the
// caller to know which case they are in.
func (q *Queries) UpsertVariable(ctx context.Context, arg UpsertVariableParams) (Variable, error) {
	row := q.db.QueryRow(ctx, upsertVariable,
		arg.OwnerID,
		arg.AppID,
		arg.Key,
		arg.Value,
		arg.Sealed,
		arg.Secret,
	)
	var i Variable
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Key,
		&i.Value,
		&i.Sealed,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
