// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volumes.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createVolume = `-- name: CreateVolume :one

INSERT INTO volumes (owner_id, app_id, name, mount_path, size_bytes, class)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at
`

type CreateVolumeParams struct {
	OwnerID   string
	AppID     uuid.UUID
	Name      string
	MountPath string
	SizeBytes int64
	Class     string
}

// Storage attached to an app. Scoped by owner_id like every other resource
// query: a handler that forgets to scope produces no rows here rather than
// another team's storage.
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, createVolume,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
		arg.MountPath,
		arg.SizeBytes,
		arg.Class,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVolume = `-- name: DeleteVolume :execrows
DELETE FROM volumes
WHERE owner_id = $1 AND app_id = $2 AND name = $3
`

type DeleteVolumeParams struct {
	OwnerID string
	AppID   uuid.UUID
	Name    string
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVolume, arg.OwnerID, arg.AppID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVolume = `-- name: GetVolume :one
SELECT id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at FROM volumes
WHERE owner_id = $1 AND app_id = $2 AND name = $3
`

type GetVolumeParams struct {
	OwnerID string
	AppID   uuid.UUID
	Name    string
}

func (q *Queries) GetVolume(ctx context.Context, arg GetVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, arg.OwnerID, arg.AppID, arg.Name)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const growVolume = `-- name: GrowVolume :execrows
UPDATE volumes
SET size_bytes = $1, updated_at = now()
WHERE owner_id = $2 AND app_id = $3 AND name = $4
  AND $1::bigint > size_bytes
`

type GrowVolumeParams struct {
	SizeBytes int64
	OwnerID   string
	AppID     uuid.UUID
	Name      string
}

// Expansion only, enforced in the WHERE clause rather than by reading the row
// and comparing in Go: a check the caller performs is one a caller can skip,
// and Kubernetes cannot shrink a claim afterwards to undo it.
func (q *Queries) GrowVolume(ctx context.Context, arg GrowVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, growVolume,
		arg.SizeBytes,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVolumesForApp = `-- name: ListVolumesForApp :many
SELECT id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at FROM volumes WHERE app_id = $1 ORDER BY mount_path
`

func (q *Queries) ListVolumesForApp(ctx context.Context, appID uuid.UUID) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Name,
			&i.MountPath,
			&i.SizeBytes,
			&i.Class,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
