// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volumes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVolume = `-- name: CreateVolume :one

INSERT INTO volumes (owner_id, app_id, name, mount_path, size_bytes, class)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at
`

type CreateVolumeParams struct {
	OwnerID   string
	AppID     uuid.UUID
	Name      string
	MountPath string
	SizeBytes int64
	Class     string
}

// Storage attached to an app. Scoped by owner_id like every other resource
// query: a handler that forgets to scope produces no rows here rather than
// another team's storage.
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, createVolume,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
		arg.MountPath,
		arg.SizeBytes,
		arg.Class,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVolumeAndBump = `-- name: CreateVolumeAndBump :one
WITH created AS (
    INSERT INTO volumes (owner_id, app_id, name, mount_path, size_bytes, class)
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING volumes.id, volumes.owner_id, volumes.app_id, volumes.name, volumes.mount_path, volumes.size_bytes, volumes.class, volumes.created_at, volumes.updated_at
), bumped AS (
    UPDATE apps
    SET config_version = config_version + 1, updated_at = now()
    WHERE apps.owner_id = $1 AND apps.id = $2
      AND EXISTS (SELECT 1 FROM created)
    RETURNING config_version
)
SELECT created.id, created.owner_id, created.app_id, created.name,
       created.mount_path, created.size_bytes, created.class,
       created.created_at, created.updated_at, bumped.config_version
FROM created CROSS JOIN bumped
`

type CreateVolumeAndBumpParams struct {
	OwnerID   string
	AppID     uuid.UUID
	Name      string
	MountPath string
	SizeBytes int64
	Class     string
}

type CreateVolumeAndBumpRow struct {
	ID            uuid.UUID
	OwnerID       string
	AppID         uuid.UUID
	Name          string
	MountPath     string
	SizeBytes     int64
	Class         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ConfigVersion int64
}

func (q *Queries) CreateVolumeAndBump(ctx context.Context, arg CreateVolumeAndBumpParams) (CreateVolumeAndBumpRow, error) {
	row := q.db.QueryRow(ctx, createVolumeAndBump,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
		arg.MountPath,
		arg.SizeBytes,
		arg.Class,
	)
	var i CreateVolumeAndBumpRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const deleteVolume = `-- name: DeleteVolume :execrows
DELETE FROM volumes
WHERE owner_id = $1 AND app_id = $2 AND name = $3
`

type DeleteVolumeParams struct {
	OwnerID string
	AppID   uuid.UUID
	Name    string
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVolume, arg.OwnerID, arg.AppID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVolumeAndBump = `-- name: DeleteVolumeAndBump :one
WITH removed AS (
    DELETE FROM volumes
    WHERE volumes.owner_id = $1
      AND volumes.app_id = $2 AND volumes.name = $3
    RETURNING volumes.id, volumes.owner_id, volumes.app_id, volumes.name, volumes.mount_path, volumes.size_bytes, volumes.class, volumes.created_at, volumes.updated_at
), bumped AS (
    UPDATE apps
    SET config_version = config_version + 1, updated_at = now()
    WHERE apps.owner_id = $1 AND apps.id = $2
      AND EXISTS (SELECT 1 FROM removed)
    RETURNING config_version
)
SELECT removed.id, removed.owner_id, removed.app_id, removed.name,
       removed.mount_path, removed.size_bytes, removed.class,
       removed.created_at, removed.updated_at, bumped.config_version
FROM removed CROSS JOIN bumped
`

type DeleteVolumeAndBumpParams struct {
	OwnerID string
	AppID   uuid.UUID
	Name    string
}

type DeleteVolumeAndBumpRow struct {
	ID            uuid.UUID
	OwnerID       string
	AppID         uuid.UUID
	Name          string
	MountPath     string
	SizeBytes     int64
	Class         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ConfigVersion int64
}

func (q *Queries) DeleteVolumeAndBump(ctx context.Context, arg DeleteVolumeAndBumpParams) (DeleteVolumeAndBumpRow, error) {
	row := q.db.QueryRow(ctx, deleteVolumeAndBump, arg.OwnerID, arg.AppID, arg.Name)
	var i DeleteVolumeAndBumpRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const getVolume = `-- name: GetVolume :one
SELECT id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at FROM volumes
WHERE owner_id = $1 AND app_id = $2 AND name = $3
`

type GetVolumeParams struct {
	OwnerID string
	AppID   uuid.UUID
	Name    string
}

func (q *Queries) GetVolume(ctx context.Context, arg GetVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, arg.OwnerID, arg.AppID, arg.Name)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const growVolume = `-- name: GrowVolume :execrows
UPDATE volumes
SET size_bytes = $1, updated_at = now()
WHERE owner_id = $2 AND app_id = $3 AND name = $4
  AND $1::bigint > size_bytes
`

type GrowVolumeParams struct {
	SizeBytes int64
	OwnerID   string
	AppID     uuid.UUID
	Name      string
}

// Expansion only, enforced in the WHERE clause rather than by reading the row
// and comparing in Go: a check the caller performs is one a caller can skip,
// and Kubernetes cannot shrink a claim afterwards to undo it.
func (q *Queries) GrowVolume(ctx context.Context, arg GrowVolumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, growVolume,
		arg.SizeBytes,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const growVolumeAndBump = `-- name: GrowVolumeAndBump :one
WITH grown AS (
    UPDATE volumes
    SET size_bytes = $1, updated_at = now()
    WHERE volumes.owner_id = $2
      AND volumes.app_id = $3 AND volumes.name = $4
      AND $1::bigint > size_bytes
    RETURNING volumes.id, volumes.owner_id, volumes.app_id, volumes.name, volumes.mount_path, volumes.size_bytes, volumes.class, volumes.created_at, volumes.updated_at
), bumped AS (
    UPDATE apps
    SET config_version = config_version + 1, updated_at = now()
    WHERE apps.owner_id = $2 AND apps.id = $3
      AND EXISTS (SELECT 1 FROM grown)
    RETURNING config_version
)
SELECT grown.id, grown.owner_id, grown.app_id, grown.name,
       grown.mount_path, grown.size_bytes, grown.class,
       grown.created_at, grown.updated_at, bumped.config_version
FROM grown CROSS JOIN bumped
`

type GrowVolumeAndBumpParams struct {
	SizeBytes int64
	OwnerID   string
	AppID     uuid.UUID
	Name      string
}

type GrowVolumeAndBumpRow struct {
	ID            uuid.UUID
	OwnerID       string
	AppID         uuid.UUID
	Name          string
	MountPath     string
	SizeBytes     int64
	Class         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ConfigVersion int64
}

func (q *Queries) GrowVolumeAndBump(ctx context.Context, arg GrowVolumeAndBumpParams) (GrowVolumeAndBumpRow, error) {
	row := q.db.QueryRow(ctx, growVolumeAndBump,
		arg.SizeBytes,
		arg.OwnerID,
		arg.AppID,
		arg.Name,
	)
	var i GrowVolumeAndBumpRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AppID,
		&i.Name,
		&i.MountPath,
		&i.SizeBytes,
		&i.Class,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigVersion,
	)
	return i, err
}

const listVolumesForApp = `-- name: ListVolumesForApp :many
SELECT id, owner_id, app_id, name, mount_path, size_bytes, class, created_at, updated_at FROM volumes WHERE app_id = $1 ORDER BY mount_path
`

func (q *Queries) ListVolumesForApp(ctx context.Context, appID uuid.UUID) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Volume{}
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AppID,
			&i.Name,
			&i.MountPath,
			&i.SizeBytes,
			&i.Class,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
